spring:
  jpa:
    database-platform: it.plansoft.sql3.dialect.SQLiteDialect
    #hibernate.ddl-auto: update|none|create-drop|create
    hibernate.ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:sqlite:src/main/resources/post.db
    driver-class-name: org.sqlite.JDBC